version: '3'

tasks:
  default:
    cmds:
      - echo "Hello, World!"
    desc: "Prints a greeting message."

  greet:
    cmds:
      - echo "Greetings, {{.NAME}}!"
    desc: "Greets a person by name."
    vars:
      NAME: "User"
