# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  news:
    desc: "This task will get the latest news update"
    summary: |
      Retrieve the latest news updates.
      Usage: task news
      Required: None
    cmds:
      - curl https://lite.cnn.com
  weather:
    desc: "Get the current weather forecast"
    summary: |
      Retrieve a weather forecast for the provided ZIPCODE.
      Usage: task weather ZIPCODE=<zipcode here>
      Required: ZIPCODE
    silent: true
    requires:
      vars:
        - "ZIPCODE"
    cmds:
      - echo "It will be sunny and awesome in {{.ZIPCODE}}"
